fishcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('fish/', views.fish_index, name='fish_index'),
  path('fish/<int:fish_id>/', views.fish_detail, name='fish_detail'),
  path('fish/create/', views.FishCreate.as_view(), name='fish_create'),
  path('fish/<int:pk>/update/', views.FishUpdate.as_view(), name='fish_update'),
  path('fish/<int:pk>/delete/', views.FishDelete.as_view(), name='fish_delete'),
  path('fish/<int:fish_id>/add_catch/', views.add_catch, name='add_catch'),
  path('fish/<int:fish_id>/assoc_lure/<int:lure_id>/', views.assoc_lure, name='assoc_lure'),
  path('lures/create/', views.LureCreate.as_view(), name='lure_create'),
  path('lures/<int:pk>/', views.LureDetail.as_view(), name='lure_detail'),
  path('lures/', views.LureList.as_view(), name='lures_index'),
  path('lures/<int:pk>/update/', views.LureUpdate.as_view(), name='lures_update'),
  path('lures/<int:pk>/delete/', views.LureDelete.as_view(), name='lures_delete'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User

CATEGORIES = (
  ('F', 'Freshwater'),
  ('S', 'Saltwater'),
  ('A', 'Anadromous')
)

# Create your models here.
class Lure(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=30)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('lure_detail', kwargs={'pk': self.id})

class Fish(models.Model):
  name = models.CharField(max_length=100, default='fish')
  scientific_name = models.CharField(max_length=100, default="")
  category = models.CharField(
    max_length=1,
    choices=CATEGORIES,
    default=CATEGORIES[0][0]
  )
  picture = models.URLField(blank=True, default="")
  lures = models.ManyToManyField(Lure)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

class Caught(models.Model):
  date = models.DateField('Catch Date')
  fish = models.ForeignKey(Fish, on_delete=models.CASCADE)

  def __str__(self):
    return f"Caught on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Caught

class CaughtForm(ModelForm):
  class Meta:
    model = Caught
    fields = ['date']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Fish, Lure
from .forms import CaughtForm

class LureList(LoginRequiredMixin, ListView):
  model = Lure

class LureDetail(LoginRequiredMixin, DetailView):
  model = Lure

class LureUpdate(LoginRequiredMixin, UpdateView):
  model = Lure
  fields = ['name', 'color']

class LureDelete(LoginRequiredMixin, DeleteView):
  model = Luresuccess_url = '/lures/'

class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

def fish_index(request):
  fish = Fish.objects.filter(user=request.user)
  return render(request, 'fish/index.html', { 'fish' : fish })

@login_required
def fish_detail(request, fish_id):
  fish = Fish.objects.get(id=fish_id)
  lures_fish_doesnt_have = Lure.objects.exclude(id__in = fish.lures.all().values_list('id'))
  caught_form = CaughtForm()
  return render(request, 'fish/detail.html', { 'fish': fish, 'caught_form': caught_form, 'lures': lures_fish_doesnt_have })

class FishCreate(LoginRequiredMixin, CreateView):
  model = Fish
  fields = ['name', 'scientific_name', 'category', 'picture']
  success_url = '/fish/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class FishUpdate(LoginRequiredMixin, UpdateView):
  model = Fish
  fields = ['scientific_name', 'category', 'picture']
  success_url = '/fish/'

class FishDelete(LoginRequiredMixin, DeleteView):
  model = Fish
  success_url = '/fish/'

@login_required
def add_catch(request, fish_id):
  form = CaughtForm(request.POST)
  if form.is_valid():
    new_catch = form.save(commit=False)
    new_catch.fish_id = fish_id
    new_catch.save()
  return redirect('fish_detail', fish_id=fish_id)

class LureCreate(LoginRequiredMixin, CreateView):
  model = Lure
  fields = '__all__'

@login_required
def assoc_lure(request, fish_id, lure_id):
  Fish.objects.get(id=fish_id).lures.add(lure_id)
  return redirect('fish_detail', fish_id=fish_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('fish_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Fish Collector</h1>
<hr />
<p class="page-content">
  One fish, Two fish, Red fish, Blue fish,
Black fish, Blue fish, Old fish, New fish.
This one has a littlecar.
This one has a little star.
Say! What a lot of fish there are.
Yes. Some are red, and some are blue.
Some are old and some are new.
Some are sad, and some are glad,
And some are very, very bad.
Why are they sad and glad and bad?
I do not know, go ask your dad.
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fish Collector</title>
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light ms-5">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Fish Collector</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav m-5 px-5">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fish_index' %}">All Fish</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'lures_index' %}">All Lures</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fish_create' %}">Add a Fish</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'lure_create' %}">Add a Lure</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/fish/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static '/css/fish/fish-detail.css' %}"
/>
<script defer src="{% static 'js/fish-detail.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center">
  <div class="card" style='width: 50%;"'>
    <img src="{{ fish.picture }}" alt="picture of fish">
      <div class="card-body">
        <h5 class="card-title">{{ fish.name }}</h5>
        <p class='card-text'>{{ fish.scientific_name }}</p>
        <a href="{% url 'fish_update' fish.id %}" class="btn btn-outline-warning">Edit</a>
        <a href="{% url 'fish_delete' fish.id %}" class="btn btn-outline-danger">Delete</a>
      </div>
  </div>
</div>
<div class='d-flex flex-column w-100 justify-content-center align-items-center m-5'>
  <h3 class='mb-2'>Add A Catch</h3>
  <form 
  action="{% url 'add_catch' fish.id %}"
  method="post"
  class="mt-5"
  >
    {% csrf_token %}
    {{caught_form.as_p }}
    <button type='submit' class="btn btn-outline-success align-self-start">Record Catch</button>
  </form>
</div>
<div class="catch-container w-100 d-flex flex-column align-items-center justify-content-center mt-5">
  <h2>Catches</h2>
  {% if fish.caught_set.all.count %}
    <ul class="list-group mb-5">
      {% for caught in fish.caught_set.all %}
        <li class='list-group-item'>{{ caught.date }}</li>
      {% endfor %}
    </ul>
    <section>
      <h2>Lures Used To Catch {{ fish.name }}</h2>
      {% if fish.lures.count %}
        {% for lure in fish.lures.all %}
          <div class="lure-container">
            <div 
              class="color-block"
              style="background-color: {{ lure.color }}"
            ></div>
            <a href="{% url 'lure_detail' lure.id %}" class='text-decoration-none'>
              <p>A {{ lure.color }} {{ lure.name }}</p>
            </a>
          </div>
        {% endfor %}
      {% endif %}
    </section>
  {% else %}
    <p>{{fish.name}} has never been caught 🦄</p>
    {% endif %}
    <h3>Available Lures</h3>
    <div class="subsection-content">
      {% if lures.count %}
        {% for lure in lures.all %}
          <div class="lure-container d-flex w-75 align-items-center">
            <div 
              class="color-block"
              style="background-color: {{ toy.color }}"
            ></div>
            <a href="{% url 'lure_detail' lure.id %}" class='text-decoration-none'>
              <p>A {{ lure.color }} {{ lure.name }}</p>
            </a>
            <form action="{% url 'assoc_lure' fish.id lure.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-success m-4">Record Lure</button>
            </form>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </section>
</div>
</div>

{% endblock %}

main_app/templates/fish/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/fish/fish-index.css' %}"
/>
{% endblock %}

{% block content %}

  <section class="container d-flex w-75 flex-wrap mt-2">
    {% for fish in fish %}
      <a href="{% url 'fish_detail' fish.id %}" class="text-decoration-none text-dark">
        <div class="card m-2 flex-column justify-content-center" style='width: 18rem;height: 18rem;'>
          <img src="{{ fish.picture }}" alt="picture of fish">
            <div class="card-body">
              <h5 class="card-title">{{ fish.name }}</h5>
              <p class='card-text'>{{ fish.scientific_name }}</p>
              <p class='card-text'>{{ fish.get_category_display }}</p>
            </div>
        </div>
      </a>
    {% endfor %}
  </section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container d-flex justify-content-center align-items-center flex-column mt-5">
  <h3>Welcome To The Fish Collector</h3>
  <img src="{% static '/images/header.png' %}" alt="logo">
</section>
{% if not user.is_authenticated %}
  <section class="logo-container d-flex justify-content-center align-items-center flex-column mt-5">
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn btn-outline-primary">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/fish_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="">
  <h1>Delete Fish?</h1>
</div>
<h2>Are you sure you want to delete {{ fish.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'fish_detail' fish.id %}" 
    class="btn btn-outline-secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn btn-outline-danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/fish_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class='page-header'>
  {% if fish %}
   <h1>Edit {{ fish.name }}</h1>
  {% else %}
    <h1>Add a Fish</h1>
  {% endif %}
</div>
  <form action="" method='post' class="form-container">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">Submit!</button>
  </form>

{% endblock %}

main_app/templates/main_app/lure_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Lure?</h1>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'lure_detail' lure.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/lure_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/toys/toy-detail.css' %}"
/>
{% endblock %}

{% block content %}
  
<div class="card" style="border-color: {{ toy.color }}">
  <div class="card-bg" style="background-color: {{ toy.color }}"></div>
  <div class="card-content">
    <h2>{{ lure.name }}</h2>
    <p>A {{ lure.color }} toy</p>
  </div>
</div>
<a href="{% url 'lures_update' lure.id %}" class="btn warn">Edit</a>
<a href="{% url 'lures_delete' lure.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/lure_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
<div class="container d-flex flex-column align-items-center">
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Lure</h1>
    {% endif %}
    <img src="{% static 'images/tackle-box.png' %}" alt="tackle box"/>
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-outline-primary mt-2">Submit!</button>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/lure_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/lures/lure-index.css' %}"
/>
{% endblock %}

{% block content %}
<section class="card-container">
  {% for lure in lure_list %}
  <div class="card" style="border-color: {{ lure.color }}">
    <div class="card-bg" style="background-color: {{ lure.color }}"></div>
    <a href="{% url 'lure_detail' lure.id %}">
      <div class="card-content">
        <h2>{{ lure.name }}</h2>
        <p>A {{ lure.color }} lure</p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}